version: '3'

services:
  julia:
    image: antonioloureiro/julia_dev
    container_name: julia
    links:
      - mongo
    networks:
      - julia-mongo-network

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - julia-mongo-network

networks: 
    julia-mongo-network:
      driver: bridge
